"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# в Docker задаётся переменной окружения; значение по умолчанию — только для локальной разработки
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-p5-*8509k8dge388y*t0&9%$cvrv*!3%4+=l))%#akifdi21be')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', '1') != '0'

# через запятую; пусто — только localhost (режим отладки)
ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # статика без отдельного веб-сервера (gunicorn в Docker)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# Превью
# Показывать ли «Обзор» на этапе загрузки: файл уходит на /preview/ сразу после выбора.
# Выключено — файл только выбирается, а превью остаётся на экране результата.

PREVIEW_ON_UPLOAD = False

# Обработка
# Весь конвейер greening (разметка → подбор растений LLM → рассадка → DXF) считается в фоне:
# /upload/ сразу отвечает номером задачи, ход и результаты — /jobs/<id>/.
# Прежний путь через сервис Влада (processing.py, planting.py) больше не вызывается.

JOBS_DIR = BASE_DIR / 'jobs'
# одновременно считаемых задач: разметка Олимпийской деревни занимает несколько гигабайт
GREENING_JOBS = 1
# задача, чей статус не опрашивали дольше стольких секунд, брошена и отменяется (страница опрашивает каждые
# 1,5 с; фоновая вкладка Chrome — не реже раза в минуту). API-клиенту: опрашивайте GET /jobs/<id>/ чаще
GREENING_JOB_ABANDON_S = int(os.environ.get('GREENING_JOB_ABANDON_S', '180'))
# кэш ответов LLM общий для всех задач: повторная загрузка того же чертежа не тратит токены
GREENING_LLM_CACHE = BASE_DIR / '.llm_cache'
# сколько запросов к LLM идёт параллельно (по одной структуре или её части на запрос)
GREENING_LLM_WORKERS = int(os.environ.get('GREENING_LLM_WORKERS', '5'))
# False (или переменная окружения GREENING_LLM=0) — подбор растений правилами, без LLM и сети;
# без BASE_URL/API_KEY в .env правила включаются сами
GREENING_LLM = os.environ.get('GREENING_LLM', '1') != '0'
# None — отправлять в LLM все структуры; число — только столько крупнейших (для проверки без трат)
GREENING_LLM_LIMIT = None

# Прежний путь через сервис Влада (core/processing.py). Сейчас /upload/ его не вызывает,
# модуль и настройки оставлены: в проекте нет git, удалённое не вернуть.
PROCESS_API_URL = 'http://localhost:8000/api/v1/process'
PROCESS_API_TIMEOUT = None
